version: "3.9"
services:
  go_js:
    build: .
    container_name: chat
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - redis
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - 6379:6379
volumes:
  logvolume01: {}