version: "3.9"
services:
  chat-frontend:
    build: React-Chat/.
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - chat-backend
  chat-backend:
    build: Go-Chat/.
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - redis
  auth:
    build: Auth/.
    container_name: auth
    ports:
      - 4000:4000
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
volumes:
  logvolume01: {}