version: "3.9"
services:
  chat-frontend:
    build: React-Chat/.
    container_name: frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  chat-backend:
    build: Go-Chat/.
    container_name: backend
    ports:
      - 8000:8000
    depends_on:
      - redis
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - 6379:6379
volumes:
  logvolume01: {}